### ISSUE TITLE
How to train the network?

### ISSUE THREAD

**Issue by wangcm12** [mrluin/ESFNet-Pytorch#1]
Hi, your work is great.  I wan to train my data,can you tell me how to train my data? Thanks!

**Comment by mrluin** [comment]
Thanks for your comment!
I have some other things to do, so I will improve the instructions in the next few days.

**Comment by mrluin** [comment]
@wangcm12  Hi, I have upgraded the training instructions, you could have a try on it. If there is something wrong, let me know, thank you.
