### ISSUE TITLE
Prepare Training Data: image color & extension

### ISSUE THREAD

**Issue by deepseek** [mrluin/ESFNet-Pytorch#14]
@mrluin 
When training using my training data ([download the file here](https://github.com/mrluin/ESFNet-Pytorch/files/3293231/trainingdata.zip)), I get an error message:

```
python train.py -gpu 1
.
.
.
)
CrossEntropyLoss()
     + Visualization init ... ...
     + Loaded, Training !
Epoch 1 validation done !
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    main(config= config, args = args)
  File "train.py", line 114, in main
    visdom=viz)
  File "train.py", line 39, in for_train
    Trainer.train()
  File "/home/home/programs/ESFNet-Pytorch/BaseTrainer.py", line 285, in train
    eval_log = self._eval_epoch(epoch)
  File "/home/home/programs/ESFNet-Pytorch/BaseTrainer.py", line 451, in _eval_epoch
    ave_iou.average(), ave_acc.average(), ave_total_loss.average()))
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by deepseek** [comment]
My guess is that this issue is caused because:
- It's not accepting grayscale images, so you will need to add a grayscale to rgb conversion step in the dataloader?
- It is not accepting png and jpg files in training?

**Comment by mrluin** [comment]
I will fix them in a few days because I have some other things to do~

**Comment by deepseek** [comment]
So I was able to detect what was causing the problem,
@mrluin you need to:
Add a grayscale to rgb conversion step in the dataloader for the input images.
Add a gray bilevel conversion for the input labels.
Add support for png & jpg extensions as input for training.

Currently, as a temporary solution, I use the commands below to prepare my training data:

For the `images` folder, I converted using:
```
for i in *.png ; do convert "$i" -colorspace sRGB -type truecolor "${i%.*}.tif" ; done
rm *.png
```

For the `label` folder, I converted using:
```
for i in *.png ; do convert "$i" -colors 2 -monochrome "${i%.*}.pcx" ; done
for i in *.pcx ; do convert "$i" -colorspace gray -colors 2 -type bilevel "${i%.*}.tif" ; done
rm *.png
rm *.pcx
```

**Comment by mrluin** [comment]
Hello @deepseek ,

You could have a little modification in Dataset.

I wrote a demo for your training_data and it worked well. [link](https://gist.github.com/mrluin/1ccaf78ffc02cc01e85fd9032c237a4a)

**Comment by deepseek** [comment]
@mrluin Can you provide information on how to use [TrainingData.py](https://gist.github.com/mrluin/1ccaf78ffc02cc01e85fd9032c237a4a)

**Comment by mrluin** [comment]
@deepseek sorry for the late reply.

It is a custom `torch.utils.data.Dataset`, and you should use it to create a `torch.utils.data.DataLoader` like this:
```
My_Dataset = Training_Data(configs=configs, subset='train')
My_DataLoader = DataLoader(My_Dataset, batch_size=10, shuffle=False)
```
And iterating the dataloader in your training, validation, and evaluation phase.
```
for step, (data, target) in enumerate(My_DataLoader, start=1):
    ...
    ...
```
