### ISSUE TITLE
ESFNet-interp8x & ESFNet-mini-ex

### ISSUE THREAD

**Issue by deepseek** [mrluin/ESFNet-Pytorch#18]
@mrluin 
Can you add interp8x & mini-ex models for training.
They seem interesting, because they have higher fps & lesser parameters than base ESFNet.
You can send the code to me privately by email if you don't want to share.

**Comment by mrluin** [comment]
@deepseek 
Of course, I will add the version of interp8x & mini-ex later.
But It is worth noting that, these extremely efficient models should consider your use cases, the tiny network cannot support hard works, and the heavy-weight networks are expensive to simple works.

So you should integrate your use case into it, such as the effective receptive field in semantic segmentation tasks, the resolution of patches, to name a few.

**Comment by deepseek** [comment]
Currently, the most efficient semantic segmentation architecture is [NasUnet](https://github.com/tianbaochou/NasUnet); if you want [to read](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8681706).
interp8x seems to be initially at its level out-of-the-box.

Anyway, please don't forget to add them later.

**Comment by mrluin** [comment]
I have added the ESFNet-interp8x and ESFNet-mini-ex in ESFNet.py

* You could use ESFNet-interp8x by calling `ESFNet(config, down_factor=8, interpolate=True, dilation=True)`
* As for mini-ex version, the down sampling rate is 8 by default.
If there are some problems, please let me know.

**Comment by ashishiiti** [comment]
RuntimeError: Expected object of type torch.cuda.LongTensor but found type torch.cuda.FloatTensor for argument #3 'other'
