### ISSUE TITLE
Training & prediction of High-resolution images using Patches

### ISSUE THREAD

**Issue by deepseek** [mrluin/ESFNet-Pytorch#19]
@mrluin Thank you for your hard work,
Issue:

1. One of the biggest issues currently facing ESFNet is not being able to train & predict
 **High-resolution images** without loading the entire image into the memory.

2. Also, the images used for training & prediction are **Multi-resolution images**, they don't have identical `Hight x Width`.

Solution:

1. **Create cropped Patches** from the original High-resolution image in both training & prediction.
This will allow images to be processed without throttling the memory.
2. **Also add margins** to the cropped patches to avoid border effects.

Note: an implementation of the suggested solution is already available at the [Robin repository.](https://github.com/masyagin1998/robin)
- In-which [dataset.py](https://github.com/masyagin1998/robin/issues/2#issuecomment-449625518) creates patches with margins using the input images 
- Then train using train.py
- Finally, run binarize.py which takes input high-resolution multisized images, and recognizes it from it's patches.

Waiting for your reply

**Comment by mrluin** [comment]
@deepseek Thanks for your comment.

What does the **margins** means? 

Will cropping with overlapped slide windows meet the requirement? If it works, I will wrap `image_cropper` into the dataset, and then you could use it as the workflow:
* Create TrainingData_Dataset, here automatically crop the high-resolution images and read patches.
* Create TrainingData_DataLoader
* Using train.py to train

**Comment by deepseek** [comment]
@mrluin before you make any changes to the esfnet code, I highly suggest reading the code of [Robin.](https://github.com/masyagin1998/robin)

Robin is a good example of simple and effective method of training & prediction based on patches, steps:
1. Prepare training data [`dataset.py`](https://github.com/masyagin1998/robin/blob/master/src/dataset/dataset.py): in-which you place your images in `robin/src/dataset/input` and run `dataset.py`, it will create patches and margins depending on the size of patches that you choose.
Example of 256 patch size:
![1](https://user-images.githubusercontent.com/49877135/60843578-bbad8180-a1df-11e9-9adb-6644b4c680ce.jpg)
Notice that the original image is not a multiple of 256, instead it's 1381x368.
![2](https://user-images.githubusercontent.com/49877135/60843666-fc0cff80-a1df-11e9-9646-ed8e09cf92bb.jpg)
It increases the Canvis size "margins" and place the image in center, so that it becomes a multiple of the patch size that we selected, in this example 256. 
![3](https://user-images.githubusercontent.com/49877135/60843839-66be3b00-a1e0-11e9-8dcc-cc413774c4ba.jpg)
Then it crops the selected patch size, now the training-data is prepared.
2. Now Robin [train.py](https://github.com/masyagin1998/robin/blob/master/src/unet/train.py) using the patches, its fast and the images can fit in the memory.
3. Then, when running [binarize.py](https://github.com/masyagin1998/robin/blob/master/src/unet/binarize.py) for prediction, it applies same patch method on the input image, and recognize the patches, then merge all back to a single image.

This method is Simple, Fast & Efficient.
Thus, you need to integrate this method in ESFNet, with the ability to set the patch size at config, this would solve alot of problems.
Waiting for your reply

**Comment by deepseek** [comment]
@mrluin any updates?

**Comment by mrluin** [comment]
Sorry, I’m struggle with the paper of various NAS optimized by RL and
Gradient-descent.

I will update this issue in a day or two.

**Comment by mrluin** [comment]
@deepseek 
Hello, I have an update for this issue.

Now, you could use [dataset.py](https://github.com/mrluin/ESFNet-Pytorch/blob/master/utils/dataset.py) to get patches from high-resolution images and ground truth.
As you mentioned above, you could set `patch_size`, 'image_margin_color', and 'label_margin_color' as you wish. Then you could use PyTorch build-in methods like `Dataset` and `DataLoader` to load and train your data.

**But**, I have another question: will the margin color have an unexpected influence on the prediction?

If you have other questions, let me know.
Thanks for your comment again :D

**Comment by deepseek** [comment]
@mrluin 
You did release the `dataset.py` to create patches, but what about the prediction step? Will you give esfnet the ability to:
- Segment the desired images to be predicted, into patches.
- Then recognize them.
- Then merge the patches together for each image.

Can you share a step-by-step guide on how to use `dataset.py` to create patches of the trainingdata. Also, how to load those patches when training. Finally, how to predict an image using the patches method.

**Comment by deepseek** [comment]
P.s: if you are looking for the most advancement in semantic segmentation sector, have a look at:
M2U-Net [[github](https://github.com/laibe/M2U-Net), [paper](http://openaccess.thecvf.com/content_CVPRW_2019/papers/BIC/Laibacher_M2U-Net_Effective_and_Efficient_Retinal_Vessel_Segmentation_for_Real-World_Applications_CVPRW_2019_paper.pdf)]
Nas-Unet [[github](https://github.com/tianbaochou/NasUnet), [paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8681706)]

**Comment by mrluin** [comment]
Hi, 
In addition to `dataset.py`, I have already updated other parts of the predicting pipeline.

pipeline: 
1. get patches from high-resolution images and save in `--input/image_patches`.
2. then using `torch.utils.data.Dataset` and 'torch.utils.data.DataLoader' to load data, perform predict, and save results in '--output/patches'.
3. remerge patches to high-resolution images and save them in '--output/patches'.

You could setup by running `launcher.py`

**Note that I have only evaluated crop&remerge method, due to I do not have a proper dataset (source images are in high-resolution) if you find problems in prediction phase, tell me please.**

**Comment by deepseek** [comment]
Error 1:
```
:~/programs/ESFNet-Pytorch$ python launcher.py --input ./input --output ./output
Loaded config file successfully ...
root_dir : /home/home/programs/ESFNet-Pytorch/traindata
save_dir : /home/home/programs/ESFNet-Pytorch/traindata/save
log_dir : /home/home/programs/ESFNet-Pytorch/traindata/save/log
test_dir : /home/home/programs/ESFNet-Pytorch/traindata/save/test
test_log_dir : /home/home/programs/ESFNet-Pytorch/traindata/save/test/log
pred_dir : /home/home/programs/ESFNet-Pytorch/traindata/save/test/predict
trainset_dir : /home/home/programs/ESFNet-Pytorch/traindata/train
validset_dir : /home/home/programs/ESFNet-Pytorch/traindata/val
testset_dir : /home/home/programs/ESFNet-Pytorch/traindata/test
data_folder_name : image
target_folder_name : label
batch_size : 16
nb_classes : 2
original_size : 512
cropped_size : 256
input_size : 512
overlapped : 0
use_gpu : True
use_multi_gpus : False
device_id : 0
random_seed : 1
num_workers : 0
lr_algorithm : adam
init_lr : 5e-4
lr_decay : 1e-1
momentum : 0.9
weight_decay : 2e-4
epsilon : 1e-8
monitor : max/MIoU
init_algorithm : kaiming
loss : crossentropy
pre_trained : False
visualization : True
verbosity : 2
early_stop : 10
save_period : 10
dis_period : 20
epochs : 300
Traceback (most recent call last):
  File "launcher.py", line 115, in <module>
    patchify_and_unpatchify_test()
  File "launcher.py", line 103, in patchify_and_unpatchify_test
    c = Cropper(args=args, configs=config, predict=True)
  File "/home/home/programs/ESFNet-Pytorch/utils/dataset.py", line 60, in __init__
    self.step_x = self.configs.step_x
AttributeError: 'MyConfiguration' object has no attribute 'step_x'
```

**Comment by deepseek** [comment]
So I changed the values of utils/dataset.py to `self.step_x = 244` & `self.step_y = 244`, now I get this Error 2:
```
(enet) home@home-desktop:~/programs/ESFNet-Pytorch$ python launcher.py --input ./input --output ./output
Loaded config file successfully ...
root_dir : /home/home/programs/ESFNet-Pytorch/traindata
save_dir : /home/home/programs/ESFNet-Pytorch/traindata/save
log_dir : /home/home/programs/ESFNet-Pytorch/traindata/save/log
test_dir : /home/home/programs/ESFNet-Pytorch/traindata/save/test
test_log_dir : /home/home/programs/ESFNet-Pytorch/traindata/save/test/log
pred_dir : /home/home/programs/ESFNet-Pytorch/traindata/save/test/predict
trainset_dir : /home/home/programs/ESFNet-Pytorch/traindata/train
validset_dir : /home/home/programs/ESFNet-Pytorch/traindata/val
testset_dir : /home/home/programs/ESFNet-Pytorch/traindata/test
data_folder_name : image
target_folder_name : label
batch_size : 16
nb_classes : 2
original_size : 512
cropped_size : 256
input_size : 512
overlapped : 0
use_gpu : True
use_multi_gpus : False
device_id : 0
random_seed : 1
num_workers : 0
lr_algorithm : adam
init_lr : 5e-4
lr_decay : 1e-1
momentum : 0.9
weight_decay : 2e-4
epsilon : 1e-8
monitor : max/MIoU
init_algorithm : kaiming
loss : crossentropy
pre_trained : False
visualization : True
verbosity : 2
early_stop : 10
save_period : 10
dis_period : 20
epochs : 300
Traceback (most recent call last):
  File "launcher.py", line 115, in <module>
    patchify_and_unpatchify_test()
  File "launcher.py", line 104, in patchify_and_unpatchify_test
    patches, n_w, n_h, image_h, image_w = c.image_processor(image_path=source_image_path)
  File "/home/home/programs/ESFNet-Pytorch/utils/dataset.py", line 122, in image_processor
    patches, n_w, n_h, image_h, image_w = self.pad_and_crop_images(image=image, margin_color=self.image_margin_color)
  File "/home/home/programs/ESFNet-Pytorch/utils/dataset.py", line 78, in pad_and_crop_images
    image_y, image_x = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
```
