### ISSUE TITLE
How can I get the WHU Building Dataset? Is it open source?

### ISSUE THREAD

**Issue by xuyingxiao** [mrluin/ESFNet-Pytorch#2]
How can I get the WHU Building Dataset? Is it open source?Is there a link?

**Comment by mrluin** [comment]
Hi @xuyingxiao ,
Sorry for the late reply, the WHU Building Dataset is publicly available. 
Here is the [link.](http://study.rsgis.whu.edu.cn/pages/download/)

**Comment by deepseek** [comment]
readme was updated with the dataset link.
@mrluin close this issue.
