### ISSUE TITLE
How to use checkpoint-best.pth for prediction

### ISSUE THREAD

**Issue by deepseek** [mrluin/ESFNet-Pytorch#4]
@mrluin Thank you for your hard work,

Now that I trained my own model, how can I use the created `checkpoint-best.pth` model for prediction on an image?

**Comment by mrluin** [comment]
@deepseek Thanks for your comment. Now it only has the function of evaluation and prediction for batches of images, I will write another one for an image to fit your requirement and then comment here again. Thanks again.

**Comment by mrluin** [comment]
Hello @deepseek ,
I have written a function that only used for prediction. [https://github.com/mrluin/ESFNet-Pytorch/blob/master/BaseTester.py#L103](prediction)
The function only requires a `DataLoader`, you could modify the batch_size internally in the `DataLoader` to meet your use case. In addition, you may have some modification on the path of files in the `_save_predict` function.[https://github.com/mrluin/ESFNet-Pytorch/blob/master/BaseTester.py#L218](filepath)

**Comment by deepseek** [comment]
@mrluin can you add the options of:

`--input`: path to directory containing input images.
`--output`: path to directory to output the predicted images.
`--weight`: path to the weight to be used for prediction.
`--threads`: number of thread used for image processing & prediction.

**Comment by deepseek** [comment]
Also, how can I use `BaseTester.py` to recognize an image?
can you provide more details.

**Comment by mrluin** [comment]
@deepseek Thanks for your comments to improve this repo.
I have added the properties you mentioned above.
And for recognizing an image or images, you could use `predictor.py` and set `batch_size` in `configs.config.cfg` to meet your use case.

There might be some other bugs in this repo, if you find it, let me know~
AND, welcome to pull requests.

**Comment by deepseek** [comment]
When running `predict.py` I got error, I think that it was caused because [`import *`](https://github.com/mrluin/ESFNet-Pytorch/blob/master/data/dataset.py#L40) created a confusion between PIL.Image and PIL.Image.Image 

Here is the error:

```
(esfnet) home@home-desktop:~/programs/ESFNet-Pytorch$ mkdir input output model
(esfnet) home@home-desktop:~/programs/ESFNet-Pytorch$ cp ./Building_Detection/cropped_aerial_torch_512/save/EDANet/0531_165145/checkpoint-best.pth
(esfnet) home@home-desktop:~/programs/ESFNet-Pytorch$ cp ./Building_Detection/cropped_aerial_torch_512/train/image/1.tif ./input
```

```
(esfnet) home@home-desktop:~/programs/ESFNet-Pytorch$ python predict.py -input ./input -output ./output -weight ./model/checkpoint-best.pth 

Loaded config file successfully ...
root_dir : /home/home/programs/ESFNet-Pytorch/Building_Detection/cropped_aerial_torch_512
save_dir : /home/home/programs/ESFNet-Pytorch/Building_Detection/cropped_aerial_torch_512/save
log_dir : /home/home/programs/ESFNet-Pytorch/Building_Detection/cropped_aerial_torch_512/save/log
test_dir : /home/home/programs/ESFNet-Pytorch/Building_Detection/cropped_aerial_torch_512/save/test
test_log_dir : /home/home/programs/ESFNet-Pytorch/Building_Detection/cropped_aerial_torch_512/save/test/log
pred_dir : /home/home/programs/ESFNet-Pytorch/Building_Detection/cropped_aerial_torch_512/save/test/predict
trainset_dir : /home/home/programs/ESFNet-Pytorch/Building_Detection/cropped_aerial_torch_512/train
validset_dir : /home/home/programs/ESFNet-Pytorch/Building_Detection/cropped_aerial_torch_512/val
testset_dir : /home/home/programs/ESFNet-Pytorch/Building_Detection/cropped_aerial_torch_512/test
data_folder_name : image
target_folder_name : label
batch_size : 16
nb_classes : 2
original_size : 512
cropped_size : 256
input_size : 256
overlapped : 0
use_gpu : True
use_multi_gpus : False
device_id : 1
random_seed : 1
num_workers : 0
lr_algorithm : adam
init_lr : 5e-4
lr_decay : 1e-1
momentum : 0.9
weight_decay : 2e-4
epsilon : 1e-8
monitor : max/MIoU
init_algorithm : kaiming
loss : crossentropy
pre_trained : False
visualization : True
verbosity : 2
early_stop : 10
save_period : 10
dis_period : 20
epochs : 300
Traceback (most recent call last):
  File "predict.py", line 149, in <module>
    predictor.predict()
  File "predict.py", line 79, in predict
    for steps, (data, target, filenames) in enumerate(self.dataloader_predict, start=1):
  File "/home/home/anaconda3/envs/esfnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/home/anaconda3/envs/esfnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/home/anaconda3/envs/esfnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/home/anaconda3/envs/esfnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "predict.py", line 46, in __getitem__
    datas = Image.open(self.data_list[index])
AttributeError: type object 'Image' has no attribute 'open'
```

**Comment by deepseek** [comment]
After fixing the `AttributeError`, I ran `predict.py` again, and got another error which was probably caused because the `target` value is missing.
For now, I removed `target`, **this is only a temporary solution which must be fixed**


Below is the `ValueError`: 
```
Traceback (most recent call last):
  File "predict.py", line 150, in <module>
    predictor.predict()
  File "predict.py", line 80, in predict
    for steps, (data, target, filenames) in enumerate(self.dataloader_predict, start=1):
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by JuanDavidG1997** [comment]
Hi,
Would you please explain the process you had to undergo in order to predict with the best checkpoint?
Thank you!
