### ISSUE TITLE
Sponsoring and donating to ESFNet

### ISSUE THREAD

**Issue by deepseek** [mrluin/ESFNet-Pytorch#7]
@mrluin Thank you for your hard work,

In-order to ensure that the ESFNet repository keeps improving, I would like to make humble donations to help you and this project grow.
- Add `.github/FUNDING.yml` file to master so I can donate.
- [example.](https://github.com/chalk/chalk/blob/master/.github/funding.yml)

**Comment by deepseek** [comment]
@mrluin Do you accept donations?

**Comment by mrluin** [comment]
Thanks for your advice.
I’m just a master student, and I think I don’t need any donations until
now, the foundation is enough to support my research.

Thanks a ton again :D
